services:
  node-1:
    image: cluster-sharding:latest
    ports:
      - '6055'
    environment:
      CLUSTER_IP: "node-1"
      CLUSTER_PORT: 6055
      CLUSTER_SEEDS: "akka.tcp://sharded-cluster-system@node-1:6055"
    volumes:
      - data:/data:rw

  node-2:
    image: cluster-sharding:latest
    ports:
      - '6056'
    environment:
      CLUSTER_IP: "node-2"
      CLUSTER_PORT: 6056
      CLUSTER_SEEDS: "akka.tcp://sharded-cluster-system@node-1:6055"
    volumes:
      - data:/data:rw

  node-3:
    image: cluster-sharding:latest
    ports:
      - '6057'
    environment:
      CLUSTER_IP: "node-3"
      CLUSTER_PORT: 6057
      CLUSTER_SEEDS: "akka.tcp://sharded-cluster-system@node-1:6055"
    volumes:
      - data:/data:rw

volumes:
  data: ~
